import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dir = path.dirname(fileURLToPath(import.meta.url));
const ids = JSON.parse(fs.readFileSync(path.join(dir, "testids.json"), "utf8"));
const json = JSON.stringify(ids, null, 2);

fs.writeFileSync(
  path.join(dir, "testids.ts"),
  `// Generated by gen-testids.mjs. Do not edit.\nexport const TEST_IDS = ${json} as const;\n`
);
fs.writeFileSync(
  path.join(dir, "testids.py"),
  `# Generated by gen-testids.mjs. Do not edit.\nTEST_IDS = ${json}\n`
);
